name: "NuGet"

on: [workflow_dispatch]

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
    
    - name: Download Artifacts
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: ci.yml
        workflow_conclusion: success
        branch: main
        name: nugetPackages-${{github.ref_name}}

    - name: Display structure of downloaded files
      run: ls -R

    - name: Push package to NuGet.org
      run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NUGET }}  -s https://api.nuget.org/v3/index.json